import type { Graph } from "@/src/lib/graph.js";

/**
 * Curated household-name NBA players for Daily Bridge endpoints.
 * Resolved against the live snapshot so missing players are skipped gracefully.
 */
export const FAMOUS_PLAYER_NAMES = [
  "LeBron James",
  "Stephen Curry",
  "Michael Jordan",
  "Kobe Bryant",
  "Magic Johnson",
  "Kevin Durant",
  "Giannis Antetokounmpo",
  "Shaquille O'Neal",
  "Tim Duncan",
  "Larry Bird",
  "Kareem Abdul-Jabbar",
  "Hakeem Olajuwon",
  "Dwyane Wade",
  "Chris Paul",
  "James Harden",
  "Kawhi Leonard",
  "Damian Lillard",
  "Anthony Davis",
  "Joel Embiid",
  "Nikola Jokić",
  "Luka Dončić",
  "Jayson Tatum",
  "Devin Booker",
  "Kyrie Irving",
  "Russell Westbrook",
  "Paul George",
  "Jimmy Butler III",
  "Trae Young",
  "Ja Morant",
  "Victor Wembanyama",
  "Allen Iverson",
  "Derrick Rose",
  "Paul Pierce",
  "Ray Allen",
  "Kevin Garnett",
  "Dirk Nowitzki",
  "Steve Nash",
  "Charles Barkley",
  "Karl Malone",
  "John Stockton",
  "Scottie Pippen",
  "Dennis Rodman",
  "Patrick Ewing",
  "Isiah Thomas",
  "Clyde Drexler",
  "David Robinson",
  "Yao Ming",
  "Tracy McGrady",
  "Vince Carter",
  "Grant Hill",
  "Blake Griffin",
  "Chris Bosh",
  "Draymond Green",
  "Klay Thompson",
  "Anthony Edwards",
  "Paolo Banchero",
  "Donovan Mitchell",
  "Zion Williamson",
  "Carmelo Anthony",
  "Dwight Howard",
  "Wilt Chamberlain",
  "Bill Russell",
  "Julius Erving",
  "Oscar Robertson",
  "Jerry West",
  "Reggie Miller",
  "Dominique Wilkins",
  "Moses Malone",
  "Robert Parish",
  "Kevin McHale",
  "Gary Payton",
  "Jason Kidd",
  "Steve Francis",
  "Amar'e Stoudemire",
  "Manu Ginobili",
  "Tony Parker",
  "Pau Gasol",
  "Marc Gasol",
  "Bradley Beal",
  "Karl-Anthony Towns",
  "Rudy Gobert",
  "DeMar DeRozan",
  "Kyle Lowry",
  "Al Horford",
  "John Wall",
  "Ben Simmons",
  "Shai Gilgeous-Alexander",
  "Chet Holmgren",
  "Tyrese Haliburton",
  "Jalen Brunson",
  "Bam Adebayo",
  "De'Aaron Fox",
] as const;

/** Snapshot player ids for the curated famous list (deduped). */
export function famousPlayerIds(graph: Graph): Set<string> {
  const byName = new Map(graph.players.map((p) => [p.name.toLowerCase(), p.id]));
  const ids = new Set<string>();
  for (const name of FAMOUS_PLAYER_NAMES) {
    const id = byName.get(name.toLowerCase());
    if (id) ids.add(id);
  }
  return ids;
}
